# Generated by Django 6.0.3 on 2026-04-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
